/* =========================================================
   HOME-ZONES.JS
   Choose Your Zone section for homepage

   Responsibilities:
   - Store zone card data
   - Render cards into #zones-grid
   - Dynamically resize grid based on viewport
   - Reveal cards on scroll
   - Publish layout for Pacman animation
   ========================================================= */

const ZONES_IMAGE_PATH = "./images/zones/";

// REMOVED the hardcoded dims.rows and dims.cols here! 
// They are now dynamically generated by getGridDimensions()

const ZONE_TARGET_BOARD_WIDTH = 1420;
const ZONE_DOT_SIZE = 20;
const ZONE_CARD_RATIO_W = 3;
const ZONE_CARD_RATIO_H = 4;
const ZONE_CORRIDOR = 1;

let zonesResizeTimer = null;

const zonesData = [
  { title: "Arcade", subtitle: "Enter Arcade World", slug: "arcade" },
  { title: "Bumper Car", subtitle: "Ride Smash Repeat", slug: "bumper-car" },
  { title: "Bowling", subtitle: "Roll Strike Repeat", slug: "bowling" },
  { title: "Trampoline", subtitle: "Jump Play Repeat", slug: "trampoline" },
  { title: "Cricket Simulator", subtitle: "Step Into Stadium", slug: "cricket-simulator" },
  { title: "VR", subtitle: "Reality Reimagined Now", slug: "vr" },
  { title: "Adventure", subtitle: "Thrill Beyond Limits", slug: "adventure" },
  { title: "Mini Bowling", subtitle: "Pocket Size Strikes", slug: "mini-bowling" },
  { title: "SoftPlay", subtitle: "Little Joy World", slug: "soft-play" },
  { title: "Cafe & Retro", subtitle: "Fuel Your Fun", slug: "cafe-retro" }
];

/* --- Responsive Grid Calculator --- */
function getGridDimensions(containerWidth) {
  if (containerWidth < 480) {
    // Mobile: 1 Column, 10 Rows (1x10)
    return { cols: 1, rows: 10 };
  } else if (containerWidth < 925) {
    // Tablet: 2 Columns, 5 Rows (2x5)
    return { cols: 2, rows: 5 };
  } else {
    // Desktop: 5 Columns, 2 Rows (5x2)
    return { cols: 5, rows: 2 };
  }
}

function debounce(fn, delay = 140) {
  return (...args) => {
    clearTimeout(zonesResizeTimer);
    zonesResizeTimer = setTimeout(() => fn(...args), delay);
  };
}

/* --- Reveal cards on scroll --- */
function initZoneReveal() {
  const zoneCards = document.querySelectorAll(".zone-card");
  if (!zoneCards.length) return;

  if (!("IntersectionObserver" in window)) {
    zoneCards.forEach((card) => card.classList.add("is-visible"));
    return;
  }

  const observer = new IntersectionObserver(
    (entries, observer) => { // 1. Pass 'observer' as an argument here
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-visible"); // 2. Use 'add' instead of 'toggle'
          observer.unobserve(entry.target);        // 3. Stop watching this card forever
        }
      });
    },
    {
      threshold: 0.1, // Trigger when 10% of the card is visible
      rootMargin: "0px 0px -50px 0px"
    }
  );

  zoneCards.forEach((card) => observer.observe(card));
}

function packZoneCardsPacman(items, containerWidth, dims) {
  const totalCards = dims.rows * dims.cols;
  const selectedItems = items.slice(0, totalCards);
  const dotSize = ZONE_DOT_SIZE;
  const corridorSize = ZONE_CORRIDOR * dotSize;
  
  // Calculate max board width and dot allocations dynamically
  const maxBoardDots = Math.floor(Math.max(0, Math.min(containerWidth, ZONE_TARGET_BOARD_WIDTH)) / dotSize);
  const availableCardDots = maxBoardDots - (dims.cols + 1) * ZONE_CORRIDOR;
  const cardWidthDots = Math.floor(availableCardDots / dims.cols);
  const cardHeightDots = Math.max(
    1,
    Math.round((cardWidthDots * ZONE_CARD_RATIO_H) / ZONE_CARD_RATIO_W)
  );
  
  const boardWidthDots = dims.cols * cardWidthDots + (dims.cols + 1) * ZONE_CORRIDOR;
  const boardHeightDots = dims.rows * cardHeightDots + (dims.rows + 1) * ZONE_CORRIDOR;
  
  const boardWidth = boardWidthDots * dotSize;
  const boardHeight = boardHeightDots * dotSize;
  const cardWidth = cardWidthDots * dotSize;
  const cardHeight = cardHeightDots * dotSize;

  if (
    !dotSize ||
    selectedItems.length !== totalCards ||
    cardWidthDots < 1 ||
    cardHeightDots < 1
  ) {
    return null;
  }

  const grid = [];

  // FIX 1: Mark used blocks at the individual DOT level instead of Card level
  function markUsedDots(column, row, wDots, hDots) {
    const startXDot = column * (wDots + ZONE_CORRIDOR);
    const startYDot = row * (hDots + ZONE_CORRIDOR);

    for (let y = startYDot; y < startYDot + hDots; y++) {
      if (!grid[y]) grid[y] = [];
      for (let x = startXDot; x < startXDot + wDots; x++) {
        grid[y][x] = true;
      }
    }
  }

  const layoutItems = selectedItems.map((item, index) => {
    const row = Math.floor(index / dims.cols);
    const column = index % dims.cols;
    const x = (ZONE_CORRIDOR + column * (cardWidthDots + ZONE_CORRIDOR)) * dotSize;
    const y = (ZONE_CORRIDOR + row * (cardHeightDots + ZONE_CORRIDOR)) * dotSize;

    // FIX 2: Map the card boundaries into the dot grid matrix
    markUsedDots(column, row, cardWidthDots, cardHeightDots);

    return {
      ...item,
      x,
      y,
      width: cardWidth,
      height: cardHeight,
      row,
      column
    };
  });

  layoutItems.grid = grid;
  layoutItems.dotSize = dotSize;
  layoutItems.corridor = ZONE_CORRIDOR;
  
  // FIX 3: Assign rows and cols to the actual DOT totals so the animation spans the whole container
  layoutItems.cols = boardWidthDots;
  layoutItems.rows = boardHeightDots;
  
  layoutItems.boardWidth = boardWidth;
  layoutItems.boardHeight = boardHeight;
  layoutItems.cardWidth = cardWidth;
  layoutItems.cardHeight = cardHeight;

  return layoutItems;
}

function renderZoneBoard(layoutItems, zonesGrid) {
  // Sync DOM writes with the browser's paint cycle
  requestAnimationFrame(() => {
    zonesGrid.style.position = "relative";
    zonesGrid.style.width = `${layoutItems.boardWidth}px`;
    zonesGrid.style.height = `${layoutItems.boardHeight}px`;
    zonesGrid.style.margin = "0 auto";
    zonesGrid.style.setProperty("--zone-dot-size", `${layoutItems.dotSize}px`);

    layoutItems.forEach((zone) => {
      const cardEl = zonesGrid.querySelector(`.zone-card[data-slug="${zone.slug}"]`);
      if (cardEl) {
        // Group style changes
        Object.assign(cardEl.style, {
          position: "absolute",
          left: `${zone.x}px`,
          top: `${zone.y}px`,
          width: `${zone.width}px`,
          height: `${zone.height}px`,
          minHeight: `${zone.height}px`
        });
      }
    });
  });
}
function publishZoneBoard(layoutItems) {
  const board = {
    cards: layoutItems,
    grid: layoutItems.grid,       // Expose the dot-level grid array
    rows: layoutItems.rows,       // Passes the total dot rows count
    cols: layoutItems.cols,       // Passes the total dot columns count
    corridorSize: layoutItems.corridor * layoutItems.dotSize,
    cardWidth: layoutItems.cardWidth,
    cardHeight: layoutItems.cardHeight,
    boardWidth: layoutItems.boardWidth,
    boardHeight: layoutItems.boardHeight
  };

  window.zoneGameBoard = board;
  window.dispatchEvent(
    new CustomEvent("zone-board-ready", {
      detail: board
    })
  );
}  

function runZoneBoardLayout() {
  const zonesGrid = document.getElementById("zones-grid");
  if (!zonesGrid) return;

  const sectionEl = document.querySelector(".home-zones");
  const container = sectionEl?.querySelector(".container");
  const containerWidth = Math.max(0, Math.floor((container || zonesGrid).clientWidth));
  
  // ==========================================
  // NEW MOBILE ABORT LOGIC
  // ==========================================
  if (window.innerWidth < 768) {
    // 1. Reset Grid Styles
    zonesGrid.style = "";
    
    // 2. Clear JS inline styles from cards so CSS takes over
    document.querySelectorAll(".zone-card").forEach(card => {
      card.style.position = "";
      card.style.left = "";
      card.style.top = "";
      card.style.width = ""; 
      card.style.height = "";
      card.style.minHeight = "";
    });

    // 3. Purge Pac-Man DOM elements instantly
    const pacmanEls = zonesGrid.querySelectorAll('#pacman-actor, .pac-dot, .pac-power-pellet, .pacman-ghost');
    pacmanEls.forEach(el => el.remove());

    // 4. Run scroll reveal and STOP the script
    initZoneReveal();
    return; 
  }

  // Apply our new dynamic dimension calculator
  const dims = getGridDimensions(containerWidth);
  const layoutItems = packZoneCardsPacman(zonesData, containerWidth, dims);

  if (!layoutItems) {
    zonesGrid.innerHTML = "";
    zonesGrid.style.height = "0px";
    return;
  }

  renderZoneBoard(layoutItems, zonesGrid);
  initZoneReveal();
  publishZoneBoard(layoutItems);
}

const rerunZoneBoardLayout = debounce(() => {
  runZoneBoardLayout();
}, 160);

/* --- Main zones init --- */
export function initZones() {
  const zonesGrid = document.getElementById("zones-grid");
  if (!zonesGrid) return;

  runZoneBoardLayout();
  window.removeEventListener("resize", rerunZoneBoardLayout);
  window.addEventListener("resize", rerunZoneBoardLayout, { passive: true });
}